apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: logsgenerator:3.2
        env:
        - name: PROCESSOR_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: processorUrl
        - name: RECEIVER_URL
          valueFrom:      
            configMapKeyRef:
              name: my-config
              key: receiverUrl
        - name: DEFAULT_LOG_COUNT
          value: "500"
        ports:
        - containerPort: 5000