apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generator-role
  namespace: logsgenerator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: processor-role
  namespace: logsprocessor
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer-role
  namespace: logsviewer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]