apiVersion: v1
kind: ServiceAccount
metadata:
  name: generator-sa
  namespace: logsgenerator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processor-sa
  namespace: logsprocessor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-sa
  namespace: logsviewer