name: Build and Push Images

on:
  push:
    branches:
      - master
    paths:
      - 'logsviewer/**'
      - 'logsgenerator/**'
      - 'logsprocessor/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        service:
          - logsviewer
          - logsgenerator
          - logsprocessor

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build \
            -t yash2505/${{ matrix.service }}:${{ github.sha }} \
            ./${{ matrix.service }}

      - name: Push Image
        run: |
          docker push yash2505/${{ matrix.service }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: azure/setup-kubectl@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Update image tags
      run: |
        sed -i "s|IMAGE_TAG|${{ github.sha }}|g" $(find . -name "*.yml")

    - name: Deploy
      run: |
        kubectl apply -R -f .